sudo: required
language: nix

before_install:
  - nix-channel --add https://nix.dapphub.com/pkgs/dapphub
  - nix-channel --update
  - nix-env -iA dapphub.{dapp,seth,hevm,evmdis}
  
script: ./.travis-test
