sudo: required
dist: trusty
language: python
python:
  - "3.6"
before_script:
#  - sudo apt-get install libssl-dev
#  - pip install mythril
  - curl https://nixos.org/nix/install | sh
  - . ~/.nix-profile/etc/profile.d/nix.sh
#  - nix-channel --add https://nix.dapphub.com/pkgs/dapphub
#  - nix-channel --update
#  - nix-env -iA dapphub.{dapp,seth,hevm,evmdis}
  - git clone --recursive https://github.com/dapphub/nixpkgs-overlay dapphub
  - nix-env -f ./dapphub -iA dapp hevm seth
script:
  - ./.travis-test
#  - mythril -x src/DappTutorial.sol