sudo: required
language: nix

before_install:
  - nix-channel --add https://nixos.org/channels/nixos-17.09 nixpkgs
  - nix-channel --update
  - nix-env -i ShellCheck solc seth nodejs hevm git
  
script: ./.travis-test